services:
  varnish:
    image: varnish:6.0.13 # latest stable version at the time of writing
    container_name: varnish
    volumes:
      - "./default.vcl:/etc/varnish/default.vcl:ro"
    ports:
      - "8080:80"
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G
    depends_on:
      - "origin"
  origin:
    image: hilverd/web-cache-playground:0.0.1
    restart: on-failure
    container_name: origin
